#!/usr/bin/env python3
"""
Generate sample .egf ("EEG-Genetic Fusion bundle") files for the dashboard demo.

The .egf format is a small proprietary text container used by the NeuroGenix
fusion demo. It bundles, for one patient:
  - a 22-dim genetic feature vector (static per patient),
  - a per-window sequence of EEG-branch preictal probabilities + genetic score.

The dashboard parses an uploaded .egf, runs the documented fusion blend
    P_final = alpha * P_eeg + (1 - alpha) * P_genetic
and maps P_final to the 4-level clinical alert system.

Layout (line based):
    EGFUSION/1.0
    # comment lines ...
    META|patient=...|sf=256|window_sec=30|windows=N|alpha=0.50|genes=SCN1A;KCNQ2
    GENETIC|<base64 of "v0,v1,...,v21">
    PAYLOAD|<base64 of "idx,eeg,gen,phase|idx,eeg,gen,phase|...">
    END

Run:  ./venv/bin/python scripts/generate_fusion_demo_samples.py
"""

import base64
import math
import random
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent.parent / "frontend" / "dashboard" / "public" / "samples"

# Canonical 22-dim genetic feature names (matches the model pipeline)
FEATURE_NAMES = [
    "SCN1A_mutation", "SCN8A_mutation", "KCNQ2_mutation", "SCN2A_mutation",
    "KCNT1_mutation", "DEPDC5_mutation", "PCDH19_mutation", "GRIN2A_mutation",
    "GABRA1_mutation", "SCN1A_pLI", "SCN8A_pLI", "KCNQ2_pLI", "SCN2A_pLI",
    "GRIN2A_pLI", "PCDH19_pLI", "GABRA1_pLI", "polygenic_risk_score",
    "sodium_channel_interaction", "potassium_channel_interaction",
    "receptor_interaction", "prs_tier1_interaction", "mutation_burden",
]


def b64(text: str) -> str:
    return base64.b64encode(text.encode("utf-8")).decode("ascii")


def make_payload(windows):
    rows = [f"{w['idx']},{w['eeg']:.3f},{w['gen']:.3f},{w['phase']}" for w in windows]
    return "|".join(rows)


def write_egf(filename, patient, genetic_vec, genetic_score, windows, alpha=0.50, genes=""):
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "EGFUSION/1.0",
        "# EEG-Genetic Fusion model input bundle - proprietary container",
        "# Generated by the NeuroGenix fusion exporter. Do not edit by hand.",
        f"META|patient={patient}|sf=256|window_sec=30|windows={len(windows)}|alpha={alpha:.2f}|genes={genes}",
        f"GENETIC|{b64(','.join(f'{v:.3f}' for v in genetic_vec))}",
        f"PAYLOAD|{b64(make_payload(windows))}",
        "END",
        "",
    ]
    path = OUT_DIR / filename
    path.write_text("\n".join(lines))
    print(f"  wrote {path.relative_to(OUT_DIR.parent.parent.parent.parent)}  "
          f"({len(windows)} windows, genetic_score={genetic_score:.2f})")


def clamp(x, lo=0.0, hi=1.0):
    return max(lo, min(hi, x))


# ----------------------------------------------------------------------------
# Scenario builders
# ----------------------------------------------------------------------------
def scenario_focal_seizure(seed=11):
    """Medium genetic risk (single Tier-1 KCNQ2). EEG drives a clear preictal
    ramp then ictal burst; genetics provides a modest constant floor."""
    random.seed(seed)
    n = 80
    pre_start, ict_start, ict_end = 46, 62, 67
    windows = []
    for i in range(n):
        if i < pre_start:
            eeg = clamp(0.06 + random.uniform(-0.03, 0.05))
            phase = 0
        elif i < ict_start:
            r = (i - pre_start) / (ict_start - pre_start)
            eeg = clamp(0.18 + r * 0.6 + random.uniform(-0.05, 0.05))
            phase = 1
        elif i <= ict_end:
            eeg = clamp(0.82 + random.uniform(-0.06, 0.12))
            phase = 2
        else:
            r = min((i - ict_end) / 6, 1)
            eeg = clamp(0.5 * (1 - r) + 0.06)
            phase = 1 if r < 0.5 else 0
        windows.append({"idx": i, "eeg": eeg, "gen": 0.0, "phase": phase})
    # MEDIUM genetic risk — constant for the whole recording (genes don't change)
    gen_score = 0.42
    # one Tier-1 gene -> balanced trust, EEG slightly favoured
    alpha = 0.52
    for w in windows:
        w["gen"] = gen_score
    gvec = [0.0] * 22
    gvec[2] = 0.95   # KCNQ2_mutation
    gvec[9] = 1.0    # SCN1A_pLI
    gvec[11] = 0.99  # KCNQ2_pLI
    gvec[16] = 0.6   # PRS
    gvec[21] = 0.95  # mutation_burden
    return windows, gvec, gen_score, "KCNQ2", alpha


def scenario_high_genetic(seed=23):
    """High genetic risk (Tier-1 SCN1A + SCN2A). Strong, predictive genetic
    evidence -> the gate down-weights EEG; genetics keeps a high constant floor
    that pushes fusion into higher alert bands earlier."""
    random.seed(seed)
    n = 80
    pre_start, ict_start, ict_end = 52, 70, 74
    windows = []
    for i in range(n):
        if i < pre_start:
            eeg = clamp(0.08 + random.uniform(-0.03, 0.05))
            phase = 0
        elif i < ict_start:
            r = (i - pre_start) / (ict_start - pre_start)
            eeg = clamp(0.2 + r * 0.45 + random.uniform(-0.05, 0.05))
            phase = 1
        elif i <= ict_end:
            eeg = clamp(0.78 + random.uniform(-0.05, 0.12))
            phase = 2
        else:
            r = min((i - ict_end) / 5, 1)
            eeg = clamp(0.45 * (1 - r) + 0.07)
            phase = 1 if r < 0.5 else 0
        windows.append({"idx": i, "eeg": eeg, "gen": 0.0, "phase": phase})
    # HIGH genetic risk — constant; Tier-1 carrier
    gen_score = 0.68
    # strong genetic signal -> model trusts genetics more (lower EEG weight)
    alpha = 0.42
    for w in windows:
        w["gen"] = gen_score
    gvec = [0.0] * 22
    gvec[0] = 1.0    # SCN1A_mutation (Tier 1)
    gvec[3] = 0.9    # SCN2A_mutation
    gvec[9] = 1.0    # SCN1A_pLI
    gvec[12] = 1.0   # SCN2A_pLI
    gvec[16] = 1.8   # PRS (high, standardised)
    gvec[17] = 0.9   # sodium_channel_interaction
    gvec[20] = 1.7   # prs_tier1_interaction
    gvec[21] = 1.9   # mutation_burden
    return windows, gvec, gen_score, "SCN1A;SCN2A", alpha


def scenario_stable(seed=37):
    """Low genetic risk (no pathogenic variants). Genetics is uninformative, so
    the gate leans on EEG; the recording stays interictal -> true negative."""
    random.seed(seed)
    n = 72
    windows = []
    for i in range(n):
        eeg = clamp(0.05 + random.uniform(-0.03, 0.07) + 0.02 * math.sin(i / 5))
        windows.append({"idx": i, "eeg": eeg, "gen": 0.0, "phase": 0})
    # LOW genetic risk — constant
    gen_score = 0.12
    # weak genetic signal -> EEG dominates (higher EEG weight)
    alpha = 0.62
    for w in windows:
        w["gen"] = gen_score
    gvec = [0.0] * 22
    gvec[9] = 1.0    # SCN1A_pLI (constraint present but no mutation)
    gvec[16] = -0.4  # PRS below average
    return windows, gvec, gen_score, "none", alpha


def main():
    print(f"Generating .egf demo samples into {OUT_DIR} ...")
    w, g, gs, genes, alpha = scenario_high_genetic()
    write_egf("patient_EGF-4490_highrisk.egf", "EGF-4490", g, gs, w, alpha=alpha, genes=genes)

    w, g, gs, genes, alpha = scenario_focal_seizure()
    write_egf("patient_EGF-7731_focal.egf", "EGF-7731", g, gs, w, alpha=alpha, genes=genes)

    w, g, gs, genes, alpha = scenario_stable()
    write_egf("patient_EGF-2208_stable.egf", "EGF-2208", g, gs, w, alpha=alpha, genes=genes)
    print("Done.")


if __name__ == "__main__":
    main()
